### PR TITLE
Improve the vault intergration, offline players can be offline

### PR DESCRIPTION
**Pull request by graywolf336**
Don't kill me, I know that iConomy 5 is super old and should die. 😂

### CODE REVIEW

**Comment by LlmDl** [comment]
doing the lords work, thank you

**Comment by LlmDl** [comment]
This came in on the IRC, from a guy who was having the Chestshop offlineplayer problem, which he says you've sorted out nicely.

```
[02:05:31] <BRock> The new iconomy jar allows me to buy/sell to offline players, but i did notice typing "money [offlineplayer]" results in "player [oflineplayer] does not have an account".

```

**Comment by graywolf336** [comment]
Yeah, that's exactly the issue which this fixes :)

**Comment by LlmDl** [comment]
BRock is saying that it still fails on using that /money [offlineplayer] command though, you may have missed that one.

**Comment by graywolf336** [comment]
Oh :o I'll take a look.

Would you mind adding me to this repository? @LlmDl

**Comment by graywolf336** [comment]
image
Seems to be working on my end...

**Pull request merged**
